version: '3'
services:
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    links:
      - influxdb:influxdb
    volumes:
      - ${PWD}/grafana:/var/lib/grafana
      - ${PWD}/dashboards:/var/lib/grafana/dashboards
      - ${PWD}/provisioning:/etc/grafana/provisioning
    networks:
      - perfiz-network
  influxgraph:
    environment:
      INFLUXGRAPH_GUNICORN_LOGLEVEL: "debug"
      INFLUXGRAPH_GUNICORN_TIMEOUT: "300"
      INFLUXGRAPH_GUNICORN_WORKERS: "2"
    image: "influxgraph/influxgraph"
    links:
      - influxdb:influxdb
    ports:
      - "8000:80"
    networks:
      - perfiz-network
  influxdb:
    environment:
      INFLUXDB_REPORTING_DISABLED: "true"
      INFLUXDB_GRAPHITE_ENABLED: "true"
      INFLUXDB_GRAPHITE_TEMPLATES: "measurement.field*"
      INFLUXDB_GRAPHITE_DATABASE: "telegraf"
    image: "influxdb"
    ports:
      - "8086:8086"
      - "2003:2003"
    volumes:
      - ${PWD}/influxdb:/var/lib/influxdb
    networks:
      - perfiz-network

networks:
  perfiz-network:
    name: "perfiz-network"
